# Generated by Django 5.0.6 on 2024-07-11 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_clothes_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='created_at',
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='images',
            field=models.ImageField(default=1, upload_to='images foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='category',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(upload_to='image foto'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='clothes',
            name='country',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.country'),
        ),
    ]
