# Generated by Django 5.0.6 on 2024-07-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_country_remove_clothes_created_at_clothes_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='country',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
